version: 2

builds:
  - main: ./cmd/sidecar
    binary: sidecar
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - CHANGELOG.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - repository:
      owner: marcus
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/marcus/sidecar"
    description: "A TUI dashboard for AI coding agents"
    license: "MIT"
    install: |
      ldflags = "-s -w -X main.Version=#{version}"
      system "go", "build", *std_go_args(ldflags:), "./cmd/sidecar"
    test: |
      assert_match version.to_s, shell_output("#{bin}/sidecar --version")
    dependencies:
      - name: go
        type: build
    url_template: "https://github.com/marcus/sidecar/archive/refs/tags/{{ .Tag }}.tar.gz"
