package jj

import (
	"regexp"
	"strings"

	"github.com/charmbracelet/x/ansi"
)

var statusPrefixToKind = map[byte]ChangeKind{
	'A': ChangeAdded,
	'M': ChangeModified,
	'D': ChangeDeleted,
	'R': ChangeRenamed,
	'C': ChangeCopied,
}

var graphCommitIDRe = regexp.MustCompile(`\b([0-9a-f]{8})\s*$`)

// ParseStatusOutput parses `jj status` output into a StatusSnapshot.
// It only extracts simple per-path lines (e.g. "M path/to/file").
func ParseStatusOutput(out string) StatusSnapshot {
	s := StatusSnapshot{
		Raw: out,
	}

	lines := strings.Split(out, "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if len(trimmed) < 2 {
			continue
		}
		if trimmed[1] != ' ' {
			continue
		}
		kind, ok := statusPrefixToKind[trimmed[0]]
		if !ok {
			continue
		}
		path := strings.TrimSpace(trimmed[2:])
		if path == "" {
			continue
		}
		s.Changes = append(s.Changes, Change{
			Kind: kind,
			Path: path,
			Raw:  line,
		})
	}
	return s
}

// ParseLogOutput parses line-oriented log output generated by logLineTemplate.
func ParseLogOutput(out string) []Commit {
	commits := make([]Commit, 0)
	lines := strings.Split(out, "\n")
	for _, line := range lines {
		if strings.TrimSpace(line) == "" {
			continue
		}
		parts := strings.SplitN(line, "\x1f", 3)
		if len(parts) < 3 {
			continue
		}
		commits = append(commits, Commit{
			ChangeID: strings.TrimSpace(parts[0]),
			CommitID: strings.TrimSpace(parts[1]),
			Subject:  strings.TrimSpace(parts[2]),
		})
	}
	return commits
}

// ParseStructuredLogOutput parses structured log output with 12 \x1f-delimited fields per line.
// Fields: changeID, commitID, description, author, timestamp, bookmarks, empty, conflict, immutable, wc, parents, shortestID
func ParseStructuredLogOutput(out string) []StructuredCommit {
	var commits []StructuredCommit
	for _, line := range strings.Split(out, "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}
		parts := strings.SplitN(line, "\x1f", 12)
		if len(parts) < 11 {
			continue
		}
		var parents []string
		if p := strings.TrimSpace(parts[10]); p != "" {
			parents = strings.Split(p, ",")
		}
		var changeIDShort string
		if len(parts) >= 12 {
			changeIDShort = strings.TrimSpace(parts[11])
		}
		commits = append(commits, StructuredCommit{
			ChangeID:      strings.TrimSpace(parts[0]),
			ChangeIDShort: changeIDShort,
			CommitID:      strings.TrimSpace(parts[1]),
			Description:   strings.TrimSpace(parts[2]),
			Author:        strings.TrimSpace(parts[3]),
			Timestamp:     strings.TrimSpace(parts[4]),
			Bookmarks:     strings.TrimSpace(parts[5]),
			IsEmpty:       strings.TrimSpace(parts[6]) == "empty",
			IsConflict:    strings.TrimSpace(parts[7]) == "conflict",
			IsImmutable:   strings.TrimSpace(parts[8]) == "immutable",
			IsWorkingCopy: strings.TrimSpace(parts[9]) == "wc",
			Parents:       parents,
		})
	}
	return commits
}

// ParseLogGraphOutput parses default `jj log` output into lines plus commit anchors.
func ParseLogGraphOutput(out string) LogGraph {
	lines := strings.Split(strings.TrimRight(out, "\n"), "\n")
	graph := LogGraph{
		Lines: make([]string, 0, len(lines)),
	}
	for idx, line := range lines {
		graph.Lines = append(graph.Lines, line)
		m := graphCommitIDRe.FindStringSubmatch(strings.TrimSpace(ansi.Strip(line)))
		if len(m) == 2 {
			graph.Commits = append(graph.Commits, GraphCommit{
				CommitID:  m[1],
				LineIndex: idx,
			})
		}
	}
	return graph
}
